### ISSUE TITLE
Error starting terminal on Ubuntu 20.04.4 LTS 

### ISSUE THREAD

**Issue by puthre** [OpenBB-finance/OpenBBTerminal#2125]
ValueError: SHA could not be resolved, git returned: b''

```
python terminal.py

Traceback (most recent call last):
  File "/home/puthre/OpenBBTerminal/terminal.py", line 917, in <module>
    main(
  File "/home/puthre/OpenBBTerminal/terminal.py", line 859, in main
    terminal()
  File "/home/puthre/OpenBBTerminal/terminal.py", line 496, in terminal
    setup_logging(appName)
  File "/home/puthre/OpenBBTerminal/openbb_terminal/loggers.py", line 165, in setup_logging
    commit_hash = get_commit_hash()
  File "/home/puthre/OpenBBTerminal/openbb_terminal/loggers.py", line 81, in get_commit_hash
    sha = repo.head.object.hexsha
  File "/home/puthre/anaconda3/envs/obb/lib/python3.9/site-packages/git/refs/symbolic.py", line 210, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/puthre/anaconda3/envs/obb/lib/python3.9/site-packages/git/objects/base.py", line 85, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/puthre/anaconda3/envs/obb/lib/python3.9/site-packages/git/db.py", line 43, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/home/puthre/anaconda3/envs/obb/lib/python3.9/site-packages/git/cmd.py", line 1253, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/home/puthre/anaconda3/envs/obb/lib/python3.9/site-packages/git/cmd.py", line 1240, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/home/puthre/anaconda3/envs/obb/lib/python3.9/site-packages/git/cmd.py", line 1198, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''

```

**Comment by deeleeramone** [comment]
Hello,

The Terminal has dependencies that require Ubuntu > 22.04. 

Please try updating your system:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```
and then:
```
conda activate openbb
conda update git
conda update pip
poetry install
```

**Comment by laaksonel** [comment]
@deeleeramone Can you elaborate what the required dependencies are? I'm on Ubuntu 20.04.4 LTS and launched the terminal via conda without any problems.

**Comment by deeleeramone** [comment]
I can only speak of the experience others have brought forward. I wouldn't be able to tell you what the threshold is in versioning that breaks compatibility. Not all builds of libraries have the same dependency chain, they can vary by specific source. I shall rephrase as, users have reported that updating Ubuntu to 22.04 resolved the issue for them.

If someone were to be able to provide any specific guidance for the minimum system requirements across the Linux ecosystem, that would be very helpful. Using both Poetry and Conda can muddle things, certain dependencies must be installed through Conda, and then others must be installed through Poetry. @piiq does a good job of weeding through all of the noise and would be a better person to answer this.

**Comment by colin99d** [comment]
Looks like this issue is with one of our dependencies: https://github.com/gitpython-developers/GitPython/issues/1016
