### ISSUE TITLE
[Bug]Stocks/news - command, and when adding -h, breaks - Error: list index out of range

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2267]
News function does not work in Stocks menu. It does work from the main menu.

```
2022 Aug 07, 19:41 /stocks/ $ news
Error: list index out of range

2022 Aug 07, 19:41 /stocks/ $ news -h
Error: list index out of range
```

<img width="1068" alt="Screen Shot 2022-08-07 at 4 39 27 PM" src="https://user-images.githubusercontent.com/85772166/183315624-3b06e736-790d-4062-888a-25522962aafa.png">

**Comment by jmmartinnu2** [comment]
It works. For you to have a result you have to have an asset loaded in memory. What could be interesting is to add a section that points, for example, to the most important financial newspapers and shows us a summary of the important news headlines... then it is time to add the APIs so that those who are subscribed can consult news

**Comment by colin99d** [comment]
@deeleeramone are you still having this issue? I cannot seem to recreate it.

**Comment by deeleeramone** [comment]
Yes. To recreate, `/stocks/load aapl/news -h`

<img width="760" alt="Screen Shot 2022-08-09 at 3 32 46 PM" src="https://user-images.githubusercontent.com/85772166/183773298-f9fcb55e-16a9-41ef-b2aa-aea411759ecf.png">

**Comment by colin99d** [comment]
<img width="847" alt="Screen Shot 2022-08-10 at 9 33 21 AM" src="https://user-images.githubusercontent.com/72827203/183914423-d9405ff3-3ec7-4fd4-a29e-4a70eed3d85a.png">
Maybe is this an outdated installer?

**Comment by colin99d** [comment]
If this still an issue after pulling from main can you run the terminal with `--debug` and then send a screenshot of the error.

**Comment by colin99d** [comment]
2022 Aug 10, 18:23 /stocks/ $ news
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 973, in <module>
    main(
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 916, in main
    terminal()
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 664, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 298, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 332, in call_stocks
    self.queue = self.load_class(StocksController, self.queue)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 183, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 651, in menu
    self.queue = self.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 298, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 58, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/stocks/stocks_controller.py", line 422, in call_news
    if sources[0] == "feedparser":
IndexError: list index out of range

**Comment by colin99d** [comment]
Adding this here for visibility

**Comment by deeleeramone** [comment]
Problem was user-error! The sources file was out-of-date and did not contain the fields for `Stocks/news`. Thanks!
