### ISSUE TITLE
[Bug] The application does not start for the first time

### ISSUE THREAD

**Issue by sandeeps-** [OpenBB-finance/OpenBBTerminal#2320]
**Describe the bug**
The is the output before the application crashes:
  _                     _ _
 | |                   | (_)
 | |     ___   __ _  __| |_ _ __   __ _
 | |    / _ \ / _` |/ _` | | '_ \ / _` |
 | |___| (_) | (_| | (_| | | | | | (_| |_ _ _
 |______\___/ \__,_|\__,_|_|_| |_|\__, (_|_|_)
                                   __/ |
                                  |___/

The boot up process might take a while. Please be patient...

Traceback (most recent call last):
  File "terminal.py", line 21, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/common/feedparser_view.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/decorators.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/__init__.py", line 48, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/core/api.py", line 48, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/core/groupby/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/core/groupby/generic.py", line 70, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/core/frame.py", line 157, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/core/generic.py", line 129, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/core/describe.py", line 38, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/io/formats/format.py", line 99, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "pandas/io/common.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "bz2.py", line 18, in <module>
ImportError: dlopen(/Applications/OpenBB Terminal/.OpenBB/lib-dynload/_bz2.cpython-39-darwin.so, 2): Library not loaded: @loader_path/../libbz2.dylib
  Referenced from: /Applications/OpenBB Terminal/.OpenBB/lib-dynload/_bz2.cpython-39-darwin.so
  Reason: no suitable image found.  Did find:
	/Applications/OpenBB Terminal/.OpenBB/lib-dynload/../libbz2.dylib: code signing blocked mmap() of '/Applications/OpenBB Terminal/.OpenBB/lib-dynload/../libbz2.dylib'
	/Applications/OpenBB Terminal/.OpenBB/lib-dynload/../libbz2.dylib: code signing blocked mmap() of '/Applications/OpenBB Terminal/.OpenBB/lib-dynload/../libbz2.dylib'
	/Applications/OpenBB Terminal/.OpenBB/lib-dynload/../libbz2.dylib: stat() failed with errno=1
	file system relative paths not allowed in hardened programs
[55240] Failed to execute script 'terminal' due to unhandled exception!

**To Reproduce**
Ran the following command after installing the program for the first time:
/Applications/OpenBB\ Terminal/OpenBB\ Terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/3928403/184559854-5e4334e0-4029-4a5a-be3f-17bb6189f594.png)

**Desktop (please complete the following information):**

- OS: macOS Big Sur (11.6.4)
- Python version [3.9.5]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by bgra8** [comment]
I got this exact same issue when trying to start the app.
This makes the app unusable on MacOSX.

**Comment by xavierysarn** [comment]
Same

**Comment by jseddonr12** [comment]
I was also presented with this issue.

**Comment by dagost2** [comment]
Also having the same issue.

**Comment by nikkatsa** [comment]
I am also having the same issue:

__MacOS Version:__ Big Sur 13.6.6
__Python Version:__ Python 3.8.9

**Comment by simmonsj330** [comment]
Hello all, we are working to find a solution to this bug!

**Comment by nikkatsa** [comment]
Thank you for fixing that!
Works well for me now, on version OpenBB Terminal v1.6.0

**Comment by tondi** [comment]
Same for me. I have just downloaded it and on the first run terminal the window exited. I'm using it within iTerm 2
