### ISSUE TITLE
WSL Anaconda installation error [Bug]

### ISSUE THREAD

**Issue by dimagalat** [OpenBB-finance/OpenBBTerminal#2407]
**Describe the bug**
When creating a new conda env the process fails on WSL 2.

**To Reproduce**
```
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh
bash Miniconda3-py39_4.12.0-Linux-x86_64.sh
git clone https://github.com/OpenBB-finance/OpenBBTerminal.git
cd OpenBBTerminal/
conda env create -n obb --file build/conda/conda-3-9-env.yaml
```
**Screenshots**
```
pycparser-2.21       | 100 KB    | ############################################################################# | 100%
Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 143, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda_env/installers/conda.py", line 59, in install
        unlink_link_transaction.execute()
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 277, in execute
        self.verify()
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 238, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 622, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 520, in map
        yield func(thing)
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 443, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/w/miniconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 319, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/w/miniconda3/lib/python3.9/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/w/miniconda3/pkgs/ncurses-6.3-h27087fc_1/share/terminfo/N/NCR260VT300WPP'
```

**Desktop (please complete the following information):**

- OS: Windows 11
- Python version 3.9

**Additional context**
This issue doesn't occur on Linux

**Comment by tinix84** [comment]
use poetry, for me was ok

**Comment by dimagalat** [comment]
I guess it's not critical since poetry does solve it
