### ISSUE TITLE
Installation fails with poetry or pip

### ISSUE THREAD

**Issue by jayurbain** [OpenBB-finance/OpenBBTerminal#2449]
**Describe the bug**
Followed installation instructions.

Installation fails using either:  
poetry install
or 
pip install -r requirements.txt

**To Reproduce**
pip install -r requirements.txt or poetry install

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOs Montery Version 12.4
- System: Apple MacBook Pro - M1
- Python version: 3.9

**Additional context**
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (setup.py): started
        Building wheel for qdldl (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [58 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "/private/var/folders/72/m1_77lk923306pr7qrrd7l100000gn/T/pip-install-uitca0yr/qdldl_a7bad84bd15d4d758e605e348809e5fa/setup.py", line 78, in build_extensions
                check_output(['cmake', '--version'])
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 424, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 505, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 951, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 1821, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/72/m1_77lk923306pr7qrrd7l100000gn/T/pip-install-uitca0yr/qdldl_a7bad84bd15d4d758e605e348809e5fa/setup.py", line 110, in <module>
                setup(name='qdldl',
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
                return distutils.core.setup(**attrs)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
                self.run_command(cmd)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                self.run_command(cmd_name)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
                _build_ext.run(self)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
                self.build_extensions()
              File "/private/var/folders/72/m1_77lk923306pr7qrrd7l100000gn/T/pip-install-uitca0yr/qdldl_a7bad84bd15d4d758e605e348809e5fa/setup.py", line 80, in build_extensions
                raise RuntimeError("CMake must be installed to build qdldl")
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
        Running setup.py clean for qdldl
      Failed to build qdldl
      Installing collected packages: wheel, typing-extensions, tomli, setuptools, pyparsing, numpy, scipy, packaging, oldest-supported-numpy, setuptools_scm, qdldl
        Running setup.py install for qdldl: started
        Running setup.py install for qdldl: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for qdldl did not run successfully.
        │ exit code: 1
        ╰─> [62 lines of output]
            running install
            /Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_ext
            Traceback (most recent call last):
              File "/private/var/folders/72/m1_77lk923306pr7qrrd7l100000gn/T/pip-install-uitca0yr/qdldl_a7bad84bd15d4d758e605e348809e5fa/setup.py", line 78, in build_extensions
                check_output(['cmake', '--version'])
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 424, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 505, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 951, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/subprocess.py", line 1821, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/72/m1_77lk923306pr7qrrd7l100000gn/T/pip-install-uitca0yr/qdldl_a7bad84bd15d4d758e605e348809e5fa/setup.py", line 110, in <module>
                setup(name='qdldl',
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
                return distutils.core.setup(**attrs)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
                self.run_command(cmd)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
                return orig.install.run(self)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
                self.run_command('build')
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
                self.run_command(cmd_name)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
                self.distribution.run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
                super().run_command(command)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
                cmd_obj.run()
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
                _build_ext.run(self)
              File "/Users/jayurbain/opt/miniconda3/envs/obb/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
                self.build_extensions()
              File "/private/var/folders/72/m1_77lk923306pr7qrrd7l100000gn/T/pip-install-uitca0yr/qdldl_a7bad84bd15d4d758e605e348809e5fa/setup.py", line 80, in build_extensions
                raise RuntimeError("CMake must be installed to build qdldl")
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> qdldl
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by deeleeramone** [comment]
Hello, you can resolve this issue with: `conda install cmake`. After this installs, run `poetry install` again. 

However, things are more stable when the x86/x64 Intel version of Miniconda is installed, instead of the M1/ARM version.

**Comment by minhhoang1023** [comment]
@jayurbain Have you managed to resolve the issue with @deeleeramone 's suggestions?

**Comment by vvatikiotis** [comment]
Did the tricks for me, cheers.

**Comment by colin99d** [comment]
This happens when people use Miniforge as their Conda environment. Miniconda does not encounter this issue.
