### ISSUE TITLE
[Bug] Crypto - Entering DD menu prints 3 error messages - Error: string indices must be integers

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2778]
![Screen Shot 2022-10-10 at 10 27 38 PM](https://user-images.githubusercontent.com/85772166/195004219-8ae96559-24b3-416e-8ca8-ccb242611f07.png)

![Screen Shot 2022-10-10 at 10 31 02 PM](https://user-images.githubusercontent.com/85772166/195004567-65eb0dd1-f8be-41b5-bbbd-a87f9924aa1e.png)

**Comment by Jrryy** [comment]
Have you set the `API_TOKEN_TERMINAL_KEY` environment variable? If you haven't, there's the problem.

**Comment by colin99d** [comment]
I do not have that key set and I could not reproduce this issue.

**Comment by deeleeramone** [comment]
I have not set that environment variable, however, it should not matter if the variable is defined. 

<img width="831" alt="Screen Shot 2022-10-14 at 10 24 54 AM" src="https://user-images.githubusercontent.com/85772166/195905762-3f5d8da3-8602-41cd-b08b-b57543bc73f8.png">

@jmaslek, here's the stack trace:
```
2022 Oct 14, 13:26 (🦋) /crypto/ $ dd
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 1020, in <module>
    main(
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 961, in main
    terminal()
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 708, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 62, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 325, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 365, in call_crypto
    self.queue = self.load_class(CryptoController, self.queue)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 206, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 837, in menu
    self.queue = self.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 62, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 325, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 62, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/cryptocurrency/crypto_controller.py", line 406, in call_dd
    self.queue = self.load_class(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 206, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/cryptocurrency/due_diligence/dd_controller.py", line 194, in __init__
    c: None for c in tokenterminal_model.get_project_ids()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 62, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/cryptocurrency/due_diligence/tokenterminal_model.py", line 53, in get_project_ids
    return [project["project_id"] for project in PROJECTS_DATA]
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/cryptocurrency/due_diligence/tokenterminal_model.py", line 53, in <listcomp>
    return [project["project_id"] for project in PROJECTS_DATA]
TypeError: string indices must be integers
```

**Comment by colin99d** [comment]
I could not reproduce this issue BUT I found it a different way and I THINK this will fix. Also @deeleeramone is right, no keys is no an excuse for errors.

**Comment by colin99d** [comment]
@deeleeramone can you use this branch and see if the issues persist: 
https://github.com/OpenBB-finance/OpenBBTerminal/pull/2845

**Comment by colin99d** [comment]
If the issue still persists please run the terminal in --debug mode and then send a screenshot of the stack trace.

**Comment by Jrryy** [comment]
I agree, instead of a raw error, the user should receive a more understandable message. I assumed the issue was that no data was being shown instead of that a raw error should be more gracefully handled.
