### ISSUE TITLE
[Bug] /crypto/ $ price -s BTC

### ISSUE THREAD

**Issue by Chavithra** [OpenBB-finance/OpenBBTerminal#3411]
**Describe the bug**
Although the price is displayed, this command generate error messages in my setup:

```bash
/crypto/ $ price -s BTC
```

Here is the error
```bash
Traceback (most recent call last):
  File "...\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "...\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "...\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "...\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
BTC-USD = 16613.702500710002 ± 12.49750071
```

**Comment by jmaslek** [comment]
:(
```
2022 Nov 14, 14:35 (🦋) /crypto/ $ price BTC

If it takes too long, you can use 'Ctrl + C' to cancel.

^CC-USD = 16495.96764226 ± 9.9049188789276001

Stopped watching BTC-USD price and confidence interval


2022 Nov 14, 14:35 (🦋) /crypto/ $ price BTC

If it takes too long, you can use 'Ctrl + C' to cancel.

^CC-USD = 16479.615 ± 4.12513.26491887

Stopped watching BTC-USD price and confidence interval


2022 Nov 14, 14:35 (🦋) /crypto/ $ price DOGE

If it takes too long, you can use 'Ctrl + C' to cancel.

^CGE-USD = 0.08507573 ± 3.862e-052.946e-05e-0500002e-05

Stopped watching DOGE-USD price and confidence interval
```

**Comment by hjoaquim** [comment]
Can't reproduce either:

![image](https://user-images.githubusercontent.com/48914296/202229842-e455dafd-0e9d-449a-b872-07c6bfbbf115.png)

**Comment by jmaslek** [comment]
@andrewkenreich also sees this.

Must be a windows thing

**Comment by Chavithra** [comment]
noted, will dig into that OS specific bug

**Comment by andrewkenreich** [comment]
https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop

looks like this could fix it
