### ISSUE TITLE
[Bug] Portfolio/bro/rh

### ISSUE THREAD

**Issue by gamerXI1** [OpenBB-finance/OpenBBTerminal#3593]
**Describe the bug**
Running history command from portfolio/brokers/rh results in error
 Error: display_historical() got an unexpected keyword argument 'span'

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
Run /portfolio/bro/rh/ $
Run login
run history -s all
Output: Error: display_historical() got an unexpected keyword argument 'span'

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

python terminal.py --debug
2022 Nov 25, 21:18 (🦋) /portfolio/bro/rh/ $ history --span all

Traceback (most recent call last):
  File "/home/adev/BBT/OpenBBTerminal/terminal.py", line 4, in <module>
    parse_args_and_run()
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 1251, in parse_args_and_run
    main(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 1156, in main
    terminal()
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 904, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 454, in call_portfolio
    self.queue = self.load_class(PortfolioController, self.queue)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 220, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 885, in menu
    self.queue = self.switch(an_input)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/portfolio/portfolio_controller.py", line 283, in call_bro
    self.queue = self.load_class(BrokersController, self.queue)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 220, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 885, in menu
    self.queue = self.switch(an_input)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/portfolio/brokers/bro_controller.py", line 64, in call_rh
    self.queue = self.load_class(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 220, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 885, in menu
    self.queue = self.switch(an_input)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/portfolio/brokers/robinhood/robinhood_controller.py", line 106, in call_history
    robinhood_view.display_historical(
  File "/home/adev/BBT/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
TypeError: display_historical() got an unexpected keyword argument 'span'

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra] : WSL2 Ubuntu - windows 11
- Python version [e.g. 3.6.8]  3.9.13

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
on it!  residual refactor kwarg that didnt get changed
