### ISSUE TITLE
[Bug] Portfolio/po - `maxdecorr -p max` - Terminal Crashes

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3594]
Error: 'numpy.float64' object has no attribute 'to_dict'

```
(🦋) /portfolio/po/ $ maxdecorr

Optimization can take time. Please be patient...

[3 Years] Maximal decorrelation portfolio

       Weights        
┏━━━━━━━━━┳━━━━━━━━━━┓
┃         ┃ Value    ┃
┡━━━━━━━━━╇━━━━━━━━━━┩
│ AAPL    │   7.35 % │
├─────────┼──────────┤
│ AMZN    │   9.98 % │
├─────────┼──────────┤
│ BTC-USD │  24.49 % │
├─────────┼──────────┤
│ GOOG    │  10.38 % │
├─────────┼──────────┤
│ K.TO    │  30.02 % │
├─────────┼──────────┤
│ MSFT    │   0.00 % │
├─────────┼──────────┤
│ SPY     │   0.00 % │
├─────────┼──────────┤
│ TSLA    │  17.78 % │
└─────────┴──────────┘

Annual (by 252) expected return: 27.11%
Annual (by √252) volatility: 28.74%
Sharpe ratio: 0.9432

(🦋) /portfolio/po/ $ maxdecorr -p max

Optimization can take time. Please be patient...

Traceback (most recent call last):
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 10, in <module>
    terminal_controller.parse_args_and_run()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 1210, in parse_args_and_run
    main(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 1129, in main
    terminal()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 906, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 456, in call_portfolio
    self.queue = self.load_class(PortfolioController, self.queue)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 219, in load_class
    return old_class.menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 893, in menu
    self.queue = self.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/portfolio/portfolio_controller.py", line 293, in call_po
    self.queue = self.load_class(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 220, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 893, in menu
    self.queue = self.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 364, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/portfolio/portfolio_optimization/po_controller.py", line 1972, in call_maxdecorr
    weights = optimizer_view.display_max_decorr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/portfolio/portfolio_optimization/optimizer_view.py", line 1868, in display_max_decorr
    weights, stock_returns = optimizer_model.get_max_decorrelation_portfolio(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/portfolio/portfolio_optimization/optimizer_model.py", line 1203, in get_max_decorrelation_portfolio
    weights = weights.squeeze().to_dict()
AttributeError: 'numpy.float64' object has no attribute 'to_dict'
```

**Comment by deeleeramone** [comment]
Maximal? Maximum?

`[3 Years] Maximal decorrelation portfolio`

![Screenshot 2022-11-25 at 11 12 39 PM](https://user-images.githubusercontent.com/85772166/204076987-63a8b858-413d-48d4-857d-e3688b1b440b.png)
