### ISSUE TITLE
[Bug] Logger Creating Issues When Creating a Build

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#3691]
**Describe the bug**
When creating my own installer the logger is causing the terminal to crash.

**To Reproduce**
- pyinstaller build/pyinstaller/terminal.spec
- cd dist/OpenBBTerminal
- ./OpenBBTerminal

**Screenshots**
```
2022 Dec 03, 10:40 (🦋) / $ Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "openbb_terminal/core/log/collection/log_sender.py", line 75, in run
    if self.check_sending_conditions(file=file):
  File "openbb_terminal/core/log/collection/log_sender.py", line 119, in check_sending_conditions
    and not self.max_size_exceeded(file=file)
  File "openbb_terminal/core/log/collection/log_sender.py", line 134, in max_size_exceeded
    return file.stat().st_size > 2 * 1024 * 1024[e] exit terminal    [cmd -h] see usage and available options    [about] G
  File "pathlib.py", line 1222, in stat
FileNotFoundError: [Errno 2] No such file or directory: '/Users/colindelahunty/OpenBBUserData/logs/ab395f98-c575-40a0-807c-7abbbbab4052/gst_packaged_1670082035.2022-12-03_10.log'
2022 Dec 03, 10:40 (🦋) / $
```

**Comment by Chavithra** [comment]
@hjoaquim any idea of the origin?

**Comment by jmaslek** [comment]
Yo @colin99d, @hjoaquim  -- this an open issue?

**Comment by hjoaquim** [comment]
I'll assume this isn't happening anymore, as we haven't had any issues creating installers in a while.
