### ISSUE TITLE
[Bug] stocks/dd/est error handling causes equity report to fail [for "TM" (toyota) ticker]

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3702]
```
Executing:  17%|███████████▌                                                         | 11/66 [00:10<00:51,  1.07cell/s]Traceback (most recent call last):
  File "[http://terminal.py](https://t.co/NVZJO9Vvpj)", line 10, in <module>
  File "openbb_terminal\terminal_controller.py", line 1210, in parse_args_and_run
    main(
  File "openbb_terminal\terminal_controller.py", line 1129, in main
    terminal()
  File "openbb_terminal\terminal_controller.py", line 796, in terminal
    log_all_settings()
  File "openbb_terminal\core\log\generation\settings_logger.py", line 41, in log_all_settings
    do_rollover()
  File "openbb_terminal\core\log\generation\settings_logger.py", line 127, in do_rollover
    handler.doRollover()
  File "openbb_terminal\core\log\generation\path_tracking_file_handler.py", line 170, in doRollover
    super().doRollover()
  File "logging\[http://handlers.py](https://t.co/n65E0mvoEz)", line 403, in doRollover
  File "logging\[http://handlers.py](https://t.co/n65E0mvoEz)", line 115, in rotate
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Jordan\\OpenBBUserData\\logs\\616d5c58-5a79-4a9a-aef3-3b63b87cb40c\\gst_packaged_1670125169' -> 'C:\\Users\\Jordan\\OpenBBUserData\\logs\\616d5c58-5a79-4a9a-aef3-3b63b87cb40c\\gst_packaged_1670125169.2022-12-03_19.log'
[2236] Failed to execute script 'terminal' due to unhandled exception!
Executing:  17%|███████████▌                                                         | 11/66 [00:13<01:05,  1.20s/cell]

An error was encountered in cell [8], check the notebook:
C:\Users\Jordan\OpenBBUserData\reports\20221203_193927_equity_tm.ipynb
```

**Comment by montezdesousa** [comment]
Seems to be a bug with yf. They are adding "k" to the EPS rows and it breaks our casting to float.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/79287829/206687069-e9ec3820-4b38-4fd4-b66e-7d0954427bd0.png">
