### ISSUE TITLE
[Bug] Run stocks > load causes "Error: can only concatenate str (not "NoneType") to str"

### ISSUE THREAD

**Issue by joshuabuildsthings** [OpenBB-finance/OpenBBTerminal#3818]
**Describe the bug**
Unable to load stocks using Yahoo Finance. 

**To Reproduce**

1. Create Conda Env
2. Install requirements using pip or poetry
3. python terminal.py
4. stocks
5. load spy
6. Get "Error: can only concatenate str (not "NoneType") to str"

**Screenshots**
```
2022 Dec 21, 21:49 (🦋) /stocks/ $ load spy

Loading Daily data for SPY with starting period 2019-12-17.
Traceback (most recent call last):
  File "c:\git-repos\stb\terminal.py", line 10, in <module>
    terminal_controller.parse_args_and_run()
  File "c:\git-repos\stb\openbb_terminal\terminal_controller.py", line 1209, in parse_args_and_run
    main(
  File "c:\git-repos\stb\openbb_terminal\terminal_controller.py", line 1128, in main
    terminal()
  File "c:\git-repos\stb\openbb_terminal\terminal_controller.py", line 905, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "c:\git-repos\stb\openbb_terminal\decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "c:\git-repos\stb\openbb_terminal\parent_classes.py", line 363, in switch
    getattr(
  File "c:\git-repos\stb\openbb_terminal\terminal_controller.py", line 377, in call_stocks
    self.queue = self.load_class(StocksController, self.queue)
  File "c:\git-repos\stb\openbb_terminal\parent_classes.py", line 219, in load_class
    return class_ins(*args, **kwargs).menu()
  File "c:\git-repos\stb\openbb_terminal\parent_classes.py", line 934, in menu
    self.queue = self.switch(an_input)
  File "c:\git-repos\stb\openbb_terminal\decorators.py", line 64, in wrapper
    value = func(*args, **kwargs)
  File "c:\git-repos\stb\openbb_terminal\parent_classes.py", line 363, in switch
    getattr(
  File "c:\git-repos\stb\openbb_terminal\parent_classes.py", line 1129, in call_load
    self.add_info = stocks_helper.additional_info_about_ticker(
  File "c:\git-repos\stb\openbb_terminal\stocks\stocks_helper.py", line 931, in additional_info_about_ticker
    extra_info += ticker_stats.get("quoteType", {}).get("shortName")
TypeError: can only concatenate str (not "NoneType") to str
```

**Desktop (please complete the following information):**

- OS: Windows
- Python version: 3.9.6

**Comment by deeleeramone** [comment]
Hello!

This has been patched, please update your local folder and installation:

```
git fetch
git pull
poetry install -E all
```

**Comment by joshuabuildsthings** [comment]
@deeleeramone - Thank you. I just updated to the latest version and still receive the error. It's a default installation; no keys entered or configuration changes.
