### ISSUE TITLE
[Bug] ImportError: cannot import name 'shellcon' from 'win32com.shell' (unknown location)

### ISSUE THREAD

**Issue by galipusta** [OpenBB-finance/OpenBBTerminal#3819]
**Describe the bug**
Sometimes after following commands
$ stocks
$ load gte

Got the following error message:

```
Exception in thread Thread-377:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "multitasking\__init__.py", line 104, in _run_via_pool
  File "yfinance\multi.py", line 199, in _download_one_threaded
  File "yfinance\multi.py", line 213, in _download_one
  File "yfinance\base.py", line 156, in history
  File "yfinance\base.py", line 339, in _get_ticker_tz
  File "yfinance\utils.py", line 434, in cache_lookup_tkr_tz
  File "yfinance\utils.py", line 425, in get_cache_dirpath
  File "appdirs.py", line 293, in user_cache_dir
  File "appdirs.py", line 480, in _get_win_folder_with_pywin32
ImportError: cannot import name 'shellcon' from 'win32com.shell' (unknown location)
```

**To Reproduce**
$ stocks
$ load gte

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 64-Bit
- Python version 3.11.1
- OpenBB version v2.1.0

**Comment by deeleeramone** [comment]
Hello,

This is likely related to Python 3.11.1 being used here. There are dependencies which are not compatible with 3.11. Please try making a new environment with Python 3.10.8:

```
conda create -n obb-new python=3.10.8
conda activate obb-new
conda install -c conda-forge git poetry cvxpy lightgbm
poetry install -E all
```

**Comment by deeleeramone** [comment]
Unknown, and beyond our control because this requires all libraries to be compatible across all platforms and architectures.

**Comment by ZimplyCode** [comment]
Hi,
Got the same issue, running
Win11 Pro 64-bit
Python v3.10.7
OpenBB v2.1.0

**Comment by redg25** [comment]
Hi,

Got the same error message with the Windows Installer.

**Comment by deeleeramone** [comment]
> 

I cannot recreate this with my Windows 11 machine. What did you use to create the Python virtual environment?

**Comment by montezdesousa** [comment]
Cannot reproduce this on Windows 11 either. 

`yfinance 0.1.9.5` tries access your cache directory and indirectly uses `pywin32` to find it, this was not in place in `yfinance 0.1.7.4` which we were using on openbb versions below v2.1.0

I'd suggest making a fresh install following these instructions https://docs.openbb.co/terminal/quickstart/installation if @deeleeramone suggestion to update `pywin` does not work.

**Comment by ZimplyCode** [comment]
> > 
> 
> I cannot recreate this with my Windows 11 machine. What did you use to create the Python virtual environment? @ZimplyCode, can you try this, inside your v2.1.0 environment? `pip install pywin`, or `python -m pip install pypiwin32`

Was using the windows installer

**Comment by ZimplyCode** [comment]
> > > 
> > 
> > 
> > I cannot recreate this with my Windows 11 machine. What did you use to create the Python virtual environment? @ZimplyCode, can you try this, inside your v2.1.0 environment? `pip install pywin`, or `python -m pip install pypiwin32`
> 
> Was using the windows installer - Will try the proposed

Couldn't (didn't give myself the time to) find the v2.1.0 environment - So I deleted
* [dir] .openbb_terminal
* [dir] OpenBB
* [dir] OpenBBUserData 
* [file] .openbb_terminal.his

Reinstalled v2.1.0, and now it works just perfect
(will try a pure python install on a Linux VM)

Cheers and thanks!
