### ISSUE TITLE
[Bug] Reports/Equity - Comparison Tab does not populate similar companies, and some other items.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3849]
To recreate: `reports/equity JPM`

```
2022 Dec 31, 15:59 (🦋) /reports/ $ equity JPM

Executing: 100%|█████████████████████████████████████████████████████████████████████| 66/66 [02:24<00:00,  1.33s/cell]Traceback (most recent call last):
  File "terminal.py", line 10, in <module>
  File "openbb_terminal\terminal_controller.py", line 1209, in parse_args_and_run
    main(
  File "openbb_terminal\terminal_controller.py", line 1128, in main
    terminal()
  File "openbb_terminal\terminal_controller.py", line 795, in terminal
    log_all_settings()
  File "openbb_terminal\core\log\generation\settings_logger.py", line 41, in log_all_settings
    do_rollover()
  File "openbb_terminal\core\log\generation\settings_logger.py", line 127, in do_rollover
    handler.doRollover()
  File "openbb_terminal\core\log\generation\path_tracking_file_handler.py", line 170, in doRollover
    super().doRollover()
  File "logging\handlers.py", line 403, in doRollover
  File "logging\handlers.py", line 115, in rotate
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Danglewood\\OpenBBUserData\\logs\\6201032e-30af-46ae-804d-4397a8c90121\\gst_packaged_1672520377' -> 'C:\\Users\\Danglewood\\OpenBBUserData\\logs\\6201032e-30af-46ae-804d-4397a8c90121\\gst_packaged_1672520377.2022-12-31_12.log'
[10764] Failed to execute script 'terminal' due to unhandled exception!
```

The report does get generated, despite the error.

All four charts are empty, and the income data table for similar companies contains only `JPM`.

Another item is that the options charts are labelled incorrectly. The charts for both, Volume and Open Interest and Option Volume, are not correct. Volume and Open Interest contains only Volume, and Option Volume contains only Open Interest.

Then the `QA` tab has a strange rendering of the monthly box plot where most other charts in the report are from the light theme:

![Screenshot_20221231_012401](https://user-images.githubusercontent.com/85772166/210155889-050a3285-4016-4c3a-8408-d932e76545ec.png)

All charts under T/A except RSI are dark-themed.

**Comment by flybfree** [comment]
I'm getting reports that crash whenever data is missing.  cell 62 - seems to be a common one (correllation sentiment) and also cell 16.  In each case, the error is due to no data available it seems.

**Comment by andrewkenreich** [comment]
closing this as these work now
