### ISSUE TITLE
[Bug] Stocks/CA/get - Terminal hangs and requires keyboard interrupt intervention

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4111]
v.2.3.1

```
stocks/load spy/ca/get
```
![Screenshot 2023-02-01 at 9 40 51 PM](https://user-images.githubusercontent.com/85772166/216241698-76985739-1b0d-4366-be96-74e865c8094c.png)

```
^CTraceback (most recent call last):
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 12, in <module>
    terminal_controller.parse_args_and_run()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 1238, in parse_args_and_run
    main(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 1157, in main
    terminal()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 934, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 366, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_controller.py", line 383, in call_stocks
    self.queue = self.load_class(StocksController, self.queue)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 223, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 914, in menu
    self.queue = self.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 366, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/stocks/stocks_controller.py", line 693, in call_ca
    self.queue = self.load_class(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 223, in load_class
    return class_ins(*args, **kwargs).menu()
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 914, in menu
    self.queue = self.switch(an_input)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/parent_classes.py", line 366, in switch
    getattr(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/stocks/comparison_analysis/ca_controller.py", line 271, in call_get
    self.similar = finviz_compare_model.get_similar_companies(
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/stocks/comparison_analysis/finviz_compare_model.py", line 43, in get_similar_companies
    Overview().compare(symbol, compare_list, verbose=0)["Ticker"].to_list()
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb-m1/lib/python3.10/site-packages/finvizfinance/screener/overview.py", line 334, in compare
    df = self.screener_view(order=order, verbose=verbose)
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb-m1/lib/python3.10/site-packages/finvizfinance/screener/overview.py", line 289, in screener_view
    sleep(sleep_sec)  # Adding sleep
KeyboardInterrupt
```

**Comment by deeleeramone** [comment]
Same behaviour when `git checkout origin/develop` where version  is 2.3.0
![Screenshot 2023-02-01 at 9 46 15 PM](https://user-images.githubusercontent.com/85772166/216242065-163e1266-7f40-447f-8951-d71c8df94a51.png)

**Comment by hjoaquim** [comment]
I think there is no issue here. For the ticker `spy` it does take a LONG time to process, but it eventually gives us a response. 
For other tickers, it is almost instant.

![image](https://user-images.githubusercontent.com/48914296/221168353-e465e33b-6096-4245-b214-063a2c5d94bc.png)

We can add some kind of timeout (eg. 20s) by using `signal`. Thoughts @jmaslek @deeleeramone ?
