### ISSUE TITLE
[Critical Bug] Installers - All Installers: Failed to execute script 'terminal' due to unhandled exception!

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4131]
Reports of installers failing to launch, across all platforms, and the error is the same. This is an issue with the installers only, cloning repo and installing the old-fashioned way works just fine. Users are currently being advised to install via the Git Clone, Conda and Poetry method.

```
Traceback (most recent call last):
  File "terminal.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/terminal_controller.py", line 27, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/terminal_helper.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "matplotlib/init.py", line 109, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "matplotlib/rcsetup.py", line 27, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "matplotlib/colors.py", line 51, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "PIL/Image.py", line 103, in <module>
ImportError: dlopen(/Applications/OpenBB Terminal/.OpenBB/PIL/_imaging.cpython-39-darwin.so, 2): Library not loaded: @loader_path/liblzma.5.dylib
  Referenced from: /Applications/OpenBB Terminal/.OpenBB/libtiff.6.dylib
  Reason: Incompatible library version: libtiff.6.dylib requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
[33102] Failed to execute script 'terminal' due to unhandled exception!
```

**Comment by kadnan** [comment]
has it been resolved yet? I am getting it on MacOS Catalina (Python 3.9)

**Comment by deeleeramone** [comment]
Best bet right now is to install via cloning the GitHub repo.

**Comment by jmaslek** [comment]
@kadnan are you on an M1 or an intel mac machine ?

**Comment by kadnan** [comment]
@jmaslek  Intel Mac

**Comment by jmaslek** [comment]
So if you are feeling adventurous, we are testing our build process.

You can try downloading our latest dev version here (download the artifact and then extract the dmg from it): https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/4106730075

Make sure to delete the OpenBB Terminal folder in your applications first!

**Comment by kadnan** [comment]
<img width="1241" alt="Screenshot 2023-02-07 at 12 14 00 PM" src="https://user-images.githubusercontent.com/273196/217173680-4541a52e-382b-4d0a-83a8-9133efccae41.png">
@jmaslek

**Comment by piiq** [comment]
Do we see this on later OSes or only Catalina?

**Comment by piiq** [comment]
It was confirmed that this issue appears only on macOS Catalina that reached EOL in October 2022. 
Folks who see this are adviced to either upgrade the OS or use the pip installable or source code versions that still work on older machines

**Comment by deeleeramone** [comment]
> 

This is not just MacOS Catalina, there have been reports from both newer Intel and M1 builds.
 
`MacBook Pro (Intel i7) macOS 11.7.1`

**Comment by andrewkenreich** [comment]
Hey ! We identified the issue here - Can you please follow these steps

```

1 - Show hidden files - 
 Command + Shift + . (period)

Then go to Applications folder > OpenBB Terminal > .OpenBB

Find the file "liblzma.5.dylib" and remove it.

Relaunch the terminal  
```

**Comment by deeleeramone** [comment]
Closing because we have this documented in the FAQ.
