### ISSUE TITLE
[Bug] pip install openbb - pydantic is not installed, module not found error

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4364]
```
(obb2) Danglewoods-MacBook-Pro:OpenBBTerminal danglewood$ openbb
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/bin/openbb", line 8, in <module>
    sys.exit(main())
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/lib/python3.10/site-packages/terminal.py", line 21, in main
    from openbb_terminal.session import session_controller
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/lib/python3.10/site-packages/openbb_terminal/session/session_controller.py", line 6, in <module>
    from openbb_terminal import terminal_controller
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/lib/python3.10/site-packages/openbb_terminal/terminal_controller.py", line 46, in <module>
    from openbb_terminal.parent_classes import BaseController
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/lib/python3.10/site-packages/openbb_terminal/parent_classes.py", line 53, in <module>
    from openbb_terminal.stocks import stocks_helper
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/lib/python3.10/site-packages/openbb_terminal/stocks/stocks_helper.py", line 59, in <module>
    from . import databento_model
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb2/lib/python3.10/site-packages/openbb_terminal/stocks/databento_model.py", line 8, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
```

**Comment by deeleeramone** [comment]
related to #4363

**Comment by jmaslek** [comment]
patching.  same issue in docker.

pip install pydantic 

will fix

**Comment by deeleeramone** [comment]
![Screenshot 2023-03-01 at 8 15 35 AM](https://user-images.githubusercontent.com/85772166/222198276-101466fa-fdc0-4a22-8754-f29640a5e708.png)

**Comment by jmaslek** [comment]
2.5.1 should fix this
