### ISSUE TITLE
[Bug] Settings/tbnews - Enabling the feature flag breaks the terminal. Crashes on restart.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4385]
![image](https://user-images.githubusercontent.com/85772166/222520255-bb8c5145-e9bd-43dc-8090-afb0517deaa4.png)

![Screenshot 2023-03-02 at 10 33 24 AM](https://user-images.githubusercontent.com/85772166/222520212-a1ca741c-fbb3-4678-a32c-980f77f8322c.png)

**Comment by jmaslek** [comment]
did this get fixed with the user model pr ?

**Comment by deeleeramone** [comment]
mmmm...don't think so. I just enabled in the `/settings` menu, and used the `reset` command.

```

Exception in thread Thread-3312 (run):
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/pywry/core.py", line 245, in run
    asyncio.run(self.connect())
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/pywry/core.py", line 193, in connect
    async with connect(
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/base_events.py", line 1028, in create_connection
    infos = await self._ensure_resolved(
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/base_events.py", line 1407, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

Then, trying to launch : `python terminal.py`

```
(obb) Danglewoods-MacBook-Pro:OpenBBTerminal danglewood$ python terminal.py
Traceback (most recent call last):
  File "/Users/danglewood/GitHub/OpenBBTerminal/terminal.py", line 7, in <module>
    from openbb_terminal.terminal_helper import is_auth_enabled
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/terminal_helper.py", line 19, in <module>
    from openbb_terminal import (
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/thought_of_the_day.py", line 10, in <module>
    from openbb_terminal.helper_funcs import request
  File "/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/helper_funcs.py", line 68, in <module>
    twitter_api.get_user(screen_name="openbb_finance")
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/tweepy/api.py", line 2508, in get_user
    return self.request(
  File "/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/tweepy/api.py", line 265, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
```

**Comment by deeleeramone** [comment]
@jmaslek  - this is still present in 3.0rc1

**Comment by montezdesousa** [comment]
@deeleeramone can you test #4603 and check if it solves your issue pls?
