### ISSUE TITLE
[Bug] Auth not grabbing certain settings

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#4423]
Please enter your credentials:
> Email: jmaslek11@gmail.com
> Password: *********
> Remember me? (y/n): n
Traceback (most recent call last):
  File "/Users/james/OpenBBTerminal/OpenBBTerminal/terminal.py", line 33, in <module>
    main()
  File "/Users/james/OpenBBTerminal/OpenBBTerminal/terminal.py", line 26, in main
    session_controller.main()
  File "/Users/james/OpenBBTerminal/OpenBBTerminal/openbb_terminal/core/session/session_controller.py", line 106, in main
    prompt()
  File "/Users/james/OpenBBTerminal/OpenBBTerminal/openbb_terminal/core/session/session_controller.py", line 77, in prompt
    return login_and_launch(session=session)
  File "/Users/james/OpenBBTerminal/OpenBBTerminal/openbb_terminal/core/session/session_controller.py", line 93, in login_and_launch
    status = login(session)
  File "/Users/james/OpenBBTerminal/OpenBBTerminal/openbb_terminal/core/session/session_model.py", line 95, in login
    if feature_settings.get("FLAIR", None) is None:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by montezdesousa** [comment]
I believe this PR https://github.com/OpenBB-finance/OpenBBTerminal/pull/4428 from @hjoaquim fixed this with `feature_settings = configs.get("features_settings", {}) or {}`

Can you check if the issue is still there @jmaslek ?

**Comment by jmaslek** [comment]
is done
