### ISSUE TITLE
linux installation fails because Installing torch (1.11.0): Failed

### ISSUE THREAD

**Issue by Dieterbe** [OpenBB-finance/OpenBBTerminal#4558]
**Describe the bug**
installation fails like so:
```
$ pip install qdldl==0.1.5.post3
poetry install -E all
(...)
 • Installing smmap (5.0.0)
  • Installing sqlalchemy (2.0.6)
  • Installing sqlglot (11.3.7)
  • Installing statsmodels (0.13.5)
  • Installing tensorboard-data-server (0.7.0)
  • Installing tensorboard-plugin-wit (1.8.1)
  • Installing torch (1.11.0): Failed

  _WheelFileValidationError

  ["In /home/dieter/.cache/pypoetry/artifacts/17/cc/19/5254fda2217804f767b6a75ecfad35b713f6f298d17167cbe221a59157/torch-1.11.0-cp310-cp310-manylinux1_x86_64.whl, hash / size of torch-1.11.0.dist-info/METADATA didn't match RECORD"]

  at ~/.conda/envs/obb/lib/python3.10/site-packages/installer/sources.py:289 in validate_record
      285│                         f"In {self._zipfile.filename}, hash / size of {item.filename} didn't match RECORD"
      286│                     )
      287│ 
      288│         if issues:
    → 289│             raise _WheelFileValidationError(issues)
      290│ 
      291│     def get_contents(self) -> Iterator[WheelContentElement]:
      292│         """Sequential access to all contents of the wheel (including dist-info files).
      293│ 

  • Installing tqdm (4.65.0)
  • Installing trace-updater (0.0.9)
(obb) ~/c/OpenBBTerminal ❯❯❯                                                                                                     
```

**To Reproduce**
follow https://docs.openbb.co/terminal/quickstart/installation for Linux

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

I tried this too:
```
(obb) ~/c/OpenBBTerminal ❯❯❯ python terminal.py --debug                                                                                                                                                         ✘ 1 
Traceback (most recent call last):
  File "/home/dieter/code/OpenBBTerminal/terminal.py", line 5, in <module>
    import openbb_terminal.config_terminal as cfg  # noqa: F401
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/__init__.py", line 13, in <module>
    from .core.plots.plotly_helper import OpenBBFigure, plots_backend, theme, TerminalStyle
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/__init__.py", line 2, in <module>
    from .plotly_helper import OpenBBFigure
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/plotly_helper.py", line 25, in <module>
    from openbb_terminal.base_helpers import console, strtobool
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/base_helpers.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
(obb) ~/c/OpenBBTerminal ❯❯❯ python3 terminal.py --debug                                                                                                                                                        ✘ 1 
Traceback (most recent call last):
  File "/home/dieter/code/OpenBBTerminal/terminal.py", line 5, in <module>
    import openbb_terminal.config_terminal as cfg  # noqa: F401
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/__init__.py", line 13, in <module>
    from .core.plots.plotly_helper import OpenBBFigure, plots_backend, theme, TerminalStyle
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/__init__.py", line 2, in <module>
    from .plotly_helper import OpenBBFigure
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/plotly_helper.py", line 25, in <module>
    from openbb_terminal.base_helpers import console, strtobool
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/base_helpers.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
(obb) ~/c/OpenBBTerminal ❯❯❯ python2 terminal.py --debug                                                                                                                                                      ✘ 130 
Traceback (most recent call last):
  File "terminal.py", line 5, in <module>
    import openbb_terminal.config_terminal as cfg  # noqa: F401
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/__init__.py", line 13, in <module>
    from .core.plots.plotly_helper import OpenBBFigure, plots_backend, theme, TerminalStyle
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/__init__.py", line 2, in <module>
    from .plotly_helper import OpenBBFigure
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/plotly_helper.py", line 52
    plt_styles_available: Dict[str, Path] = {}
                        ^
SyntaxError: invalid syntax
(obb) ~/c/OpenBBTerminal ❯❯❯ 
```

**Desktop (please complete the following information):**

- Arch Linux
- Python 3.10.10

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
Hi! The Linux installation will be improving over the next couple/few days, but in the meantime, try installing these items: https://github.com/OpenBB-finance/OpenBBTerminal/issues/4556#issuecomment-1478940152

#4556

**Comment by noubre** [comment]
I am having the same problem and installing those things didn't work. I am on Ubuntu 22.04.2

**Comment by deeleeramone** [comment]
@piiq  @andrewkenreich

**Comment by piiq** [comment]
This is a regression in poetry 1.4.1 introduced last weekend 
Try installing poetry 1.4.0 - ot should work

**Comment by deeleeramone** [comment]
> This is a regression in poetry 1.4.1 introduced last weekend
> Try installing poetry 1.4.0 - it should work


![Screenshot 2023-03-22 133656](https://user-images.githubusercontent.com/85772166/227032148-2c96c612-5308-4112-8902-01e4248c90ea.png)

**Comment by noubre** [comment]
Thanks!

**Comment by Dieterbe** [comment]
i can confirm that `pip install poetry==1.4.0 && poetry install -E all` is able to complete installation.

**Comment by piiq** [comment]
This issue can also be resolved by setting `poetry config installer.modern-installation false` as pointed out in https://github.com/microsoft/debugpy/issues/1246

**Comment by andrewkenreich** [comment]
Closing this then as it is resolved.

**Comment by piiq** [comment]
please note that the referenced debugpy issue comments report that poetry 1.4.2 doesn't have this problem
