### ISSUE TITLE
[Bug] ImportError: /usr/lib/libtracker-sparql-3.0.so.0: undefined symbol: g_task_set_static_name

### ISSUE THREAD

**Issue by Dieterbe** [OpenBB-finance/OpenBBTerminal#4567]
**Describe the bug**
after following https://docs.openbb.co/terminal/quickstart/installation instructions for Linux, and following the workaround from #4558, the terminal fails to launch:
```
python terminal.py
Traceback (most recent call last):
  File "/home/dieter/code/OpenBBTerminal/terminal.py", line 5, in <module>
    import openbb_terminal.config_terminal as cfg  # noqa: F401
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/__init__.py", line 13, in <module>
    from .core.plots.plotly_helper import OpenBBFigure, plots_backend, theme, TerminalStyle
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/__init__.py", line 2, in <module>
    from .plotly_helper import OpenBBFigure
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/plotly_helper.py", line 27, in <module>
    from openbb_terminal.core.plots.backend import PLOTLYJS_PATH, plots_backend
  File "/home/dieter/code/OpenBBTerminal/openbb_terminal/core/plots/backend.py", line 16, in <module>
    import pywry
  File "/home/dieter/.conda/envs/obb/lib/python3.10/site-packages/pywry/__init__.py", line 1, in <module>
    from .core import PyWry  # noqa: F401
  File "/home/dieter/.conda/envs/obb/lib/python3.10/site-packages/pywry/core.py", line 17, in <module>
    from pywry import pywry
ImportError: /usr/lib/libtracker-sparql-3.0.so.0: undefined symbol: g_task_set_static_name
```

**Desktop (please complete the following information):**

- OS: arch linux
- Python 3.10.9

**Comment by colin99d** [comment]
@Dieterbe did the solution above fix your issue?

**Comment by Dieterbe** [comment]
Hey. I'm on vacation but looking forward to try next next week.

**Comment by Dieterbe** [comment]
i tried a fresh install per the updated instructions on the website, and now it works fine.
i did recently perform a system update, and seems i now have webkitgtk-6.0 2.40.0-2 installed
