### ISSUE TITLE
[Bug] Faced `ImportError` when installing OpenBB in Windows

### ISSUE THREAD

**Issue by tys203831** [OpenBB-finance/OpenBBTerminal#4591]
**Describe the bug**
The bug I have faced in my Windows laptop is exactly same as this one: https://www.reddit.com/r/openBB/comments/11vi4hl/trouble_installing_openbb_beed_help/

**To Reproduce**
I follow the docs here: https://docs.openbb.co/terminal/installation/source but when I tried to type `pip install qdldl==0.1.5.post3`, the bug happens.

**Screenshots**
Here is my bug message I have faced:
<img width="638" alt="cmd_UOaTiBz1JY" src="https://user-images.githubusercontent.com/64836390/227771217-fb868c5d-eb2c-49ae-8ca8-fcd69f0836b2.png">

**Desktop (please complete the following information):**

- OS: Windows
- Python version: 3.10.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
This is why it's not working.  You are not following the instructions and are inserting your own packages which create conflicts and result in a contaminated virtual environment.

![Screenshot 2023-03-27 at 8 45 44 AM](https://user-images.githubusercontent.com/85772166/227995054-fac51bc6-1c54-4654-af32-5c63a4560d1d.png)

**Comment by colin99d** [comment]
@tys203831 did using a fresh OpenBB environment without installing other dependencies fix your issue?

**Comment by tys203831** [comment]
@colin99d @deeleeramone I remove my original conda environment and recreate a new conda environment using the commands you given instead, and I faced similar error....

Below is the code I put into the cmd:

`conda create -n openbb -c conda-forge python=3.10.9 pip pybindll cmake git cvxpy lightgbm poetry`

`conda activate openbb`

`pip install scipy syper-kernels==2.1.* scipy matplotlib sklearn pandas numpy yfinance ta tensorflow sqlalchemy psycopg2 seaborn selenium plotly py_vollib cufflinks bs4 dash dash_bootstrap_components sec_edgar_downloader poetry numpy statsmodels financedatabase`

Here is my error message:

```
Traceback (most recent call last):
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\Scripts\pip-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\utils\misc.py", line 43, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 44, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 23, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "C:\Users\yongsheng.tan\AppData\Local\miniconda3\envs\openbb\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
```

**Comment by colin99d** [comment]
@tys203831 where are you seeing that you need to install dependencies like syper-kernels and cufflinks? I believe the command you need to run is:
```
pip install qdldl==0.1.5.post3
poetry install -E all
```

**Comment by deeleeramone** [comment]
DO NOT INSTALL LIKE THIS
```
pip install scipy syper-kernels==2.1.* scipy matplotlib sklearn pandas numpy yfinance ta tensorflow sqlalchemy psycopg2 seaborn selenium plotly py_vollib cufflinks bs4 dash dash_bootstrap_components sec_edgar_downloader poetry numpy statsmodels financedatabase
```

**Comment by kovacsgyula** [comment]
I'm having the same problem. Is there a fix for this?

**Comment by ghbcode** [comment]
I am also having the same issue. Windows 10. Installed:

- VS build tools
- miniconda3 (not anaconda)
- vcxsrv 

```
(base) env is activated
conda create -n obb -c conda-forge python=3.10.9 pip pybind11 cmake git cvxpy lightgbm poetry
conda activate obb
git clone https://github.com/OpenBB-finance/OpenBBTerminal.git
cd OpenBBTerminal
pip install qdldl==0.1.5.post3
```

At the step above (pip install qdldl...) I get the error:

```
(obb) C:\Users\admin\OpenBBTerminal>pip3 install qdldl==0.1.5.post3
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\obb\Scripts\pip3-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\utils\misc.py", line 43, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 44, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 23, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\Users\admin\.conda\envs\obb\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "C:\Users\admin\.conda\envs\obb\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
```

I followed the instrux per the source install page and did NOT install any other packages like tys203831 did. This was a clean install of miniconda3 and brand new env. In fact, I tried twice. Any ideas on what the issue may be?
