### ISSUE TITLE
[Bug-launch]Critical Issue-Failed to execute script 'terminal' due to unhandled exception!

### ISSUE THREAD

**Issue by DanielWangGLOBAL** [OpenBB-finance/OpenBBTerminal#4722]
**Describe the bug**
Traceback (most recent call last):
  File "terminal.py", line 30, in <module>
  File "terminal.py", line 26, in main
  File "openbb_terminal/session/session_controller.py", line 82, in launch_terminal
  File "openbb_terminal/terminal_controller.py", line 1321, in parse_args_and_run
  File "openbb_terminal/terminal_controller.py", line 1234, in main
  File "openbb_terminal/terminal_controller.py", line 920, in terminal
  File "openbb_terminal/helper_funcs.py", line 1900, in update_news_from_tweet_to_be_displayed
  File "tweepy/api.py", line 33, in wrapper
  File "tweepy/api.py", line 46, in wrapper
  File "tweepy/api.py", line 577, in user_timeline
  File "tweepy/api.py", line 263, in request
tweepy.errors.Unauthorized: 401 Unauthorized
89 - Invalid or expired token.
[8373] Failed to execute script 'terminal' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Screenshots**
see below
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/66401013/230758529-e9ec8e2f-8326-43c2-a74e-7620440c2c3c.png">

**Desktop (please complete the following information):**
- OS: [e.g. Mac Ventura 13.2.1 Apple M1]

**Additional context**
I'm installing the latest version, still says i am not using the latest stable version. (see screenshot)
It works for a while, after exit the terminal and then reboot, the above issue prompts up.

**Comment by DanielWangGLOBAL** [comment]
@the-praxs  thanks very much. it works now.
