### ISSUE TITLE
SDK import takes minutes in terminal but is very quick in jupyter notebook [Bug] 

### ISSUE THREAD

**Issue by 99snowleopards** [OpenBB-finance/OpenBBTerminal#4921]
**Describe the bug**
`from openbb_terminal.sdk import openbb` takes minutes to execute when I run it in a Python interpreter in a terminal or run a python script

**To Reproduce**
the above import statement runs in a few seconds in a Jupyter notebook and I'm also able to start the openbb terminal immediately

**Screenshots**

I don't get any error, but this is the trace when I exit execution:

```
>>> from openbb_terminal.sdk import openbb
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/code/fin/fin_1/obb/OpenBBTerminal/openbb_terminal/sdk.py", line 18, in <module>
    import openbb_terminal.core.sdk.sdk_init as lib
  File "/home/user/code/fin/fin_1/obb/OpenBBTerminal/openbb_terminal/core/sdk/sdk_init.py", line 434, in <module>
    from openbb_terminal.forecast import (
  File "/home/user/code/fin/fin_1/obb/OpenBBTerminal/openbb_terminal/forecast/anom_model.py", line 10, in <module>
    from darts.ad import KMeansScorer, QuantileDetector
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/darts/ad/__init__.py", line 33, in <module>
    from .anomaly_model import FilteringAnomalyModel, ForecastingAnomalyModel
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/darts/ad/anomaly_model/__init__.py", line 28, in <module>
    from .filtering_am import FilteringAnomalyModel
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/darts/ad/anomaly_model/filtering_am.py", line 16, in <module>
    from darts.models.filtering.filtering_model import FilteringModel
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/darts/models/__init__.py", line 12, in <module>
    from darts.models.forecasting.auto_arima import AutoARIMA
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/darts/models/forecasting/auto_arima.py", line 8, in <module>
    from pmdarima import AutoARIMA as PmdAutoARIMA
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/pmdarima/__init__.py", line 52, in <module>
    from .arima import auto_arima, ARIMA, AutoARIMA, StepwiseContext, decompose
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/pmdarima/arima/__init__.py", line 5, in <module>
    from .approx import *
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/pmdarima/arima/approx.py", line 9, in <module>
    from ..utils.array import c, check_endog
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/pmdarima/utils/__init__.py", line 7, in <module>
    from .visualization import *
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/pmdarima/utils/visualization.py", line 24, in <module>
    mpl = get_compatible_pyplot(backend=backend, debug=debug)
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/pmdarima/compat/matplotlib.py", line 35, in get_compatible_pyplot
    existing_backend = matplotlib.get_backend()
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/matplotlib/__init__.py", line 1259, in get_backend
    return rcParams['backend']
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/matplotlib/__init__.py", line 744, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/matplotlib/pyplot.py", line 234, in switch_backend
    current_framework = cbook._get_running_interactive_framework()
  File "/home/user/anaconda3/envs/obb/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 89, in _get_running_interactive_framework
    if not _c_internal_utils.display_is_valid():
KeyboardInterrupt
>>>
```

**Desktop (please complete the following information):**

- OS: WSL2 on Windows 11
- Python version 3.9 

**Additional context**

I installed VcXsrv and Xming - VcXsrv installer does not give the option to check "Disable access control"

I'd greatly appreciate any help - thank you!

**Comment by 99snowleopards** [comment]
I installed the terminal and SDK on WSL without VcXsrv or the alternatives - installing those breaks something in the SDK import - I would add a note of caution to users that the WSL install process has not been tested thoroughly
