### ISSUE TITLE
Error: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by maread99** [OpenBB-finance/OpenBBTerminal#5162]
**Describe the bug**
In response to **most commands** in the terminal I'm getting back:

`Error: object NoneType can't be used in 'await' expression`

**To Reproduce**
I installed to a fresh conda environment following [these instructions](https://docs.openbb.co/terminal/installation/pypi).

On launching the terminal, before the menu appears I get the following print:
```
(obb) C:\Users\<user_name>>openbb
C:\Users\<user_name>\miniconda3\envs\obb\lib\site-packages\pywry\core.py:420: RuntimeWarning: coroutine 'Backend.check_backend' was never awaited
  self.check_backend()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Welcome to OpenBB Terminal v3.0.1
```

Then, for example:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/56914820/fbeb5316-9df5-41bc-b7ae-0418bb1593bb)

Calling the same command with the terminal in debug mode and, before the terminal exits, I get the print:
```
Traceback (most recent call last):
  File "C:\Users\<username>\miniconda3\envs\obb\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<username>\miniconda3\envs\obb\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\miniconda3\envs\obb\Scripts\openbb.exe\__main__.py", line 7, in <module>
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\terminal.py", line 39, in main
    session_controller.launch_terminal()
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\core\session\session_controller.py", line 83, in launch_terminal
    terminal_controller.parse_args_and_run()
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\terminal_controller.py", line 1198, in parse_args_and_run
    main(
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\terminal_controller.py", line 1111, in main
    terminal()
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\terminal_controller.py", line 880, in terminal
    t_controller.queue = t_controller.switch(an_input)
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\parent_classes.py", line 399, in switch
    getattr(
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\terminal_controller.py", line 490, in call_stocks
    self.queue = self.load_class(StocksController, self.queue)
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\parent_classes.py", line 255, in load_class
    return class_ins(*args, **kwargs).menu()
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\parent_classes.py", line 1001, in menu
    self.queue = self.switch(an_input)
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\parent_classes.py", line 399, in switch
    getattr(
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\decorators.py", line 67, in wrapper
    value = func(*args, **kwargs)
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\stocks\stocks_controller.py", line 270, in call_search
    stocks_helper.search(
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\stocks\stocks_helper.py", line 257, in search
    print_rich_table(
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\helper_funcs.py", line 337, in print_rich_table
    plots_backend().send_table(
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\core\plots\backend.py", line 264, in send_table
    self.loop.run_until_complete(self.check_backend())
  File "C:\Users\<username>\miniconda3\envs\obb\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\<username>\miniconda3\envs\obb\lib\site-packages\openbb_terminal\core\plots\backend.py", line 381, in check_backend
    await super().check_backend()
TypeError: object NoneType can't be used in 'await' expression
```

I've removed the environment and repeated the process, same result.
The SDK seems to work fine.
Separately, I've installed via the Windows Installer (as [here](https://docs.openbb.co/terminal/installation/windows)) and the terminal there works fine.

Any ideas? I don't really want to have two installations (via PyPI for the SDK and via the Windows installer for the terminal).

Thank you, and thank you for everyone's work on this great project!

**Desktop**

- OS: Windows 11 Home 22H2
- Python version 3.9.13

**Comment by jmaslek** [comment]
Can you see what version of pywry is installed?

`pip install -U pywry` 

We also released a new package, so you can do `pip install -U openbb` and that should take care of that error

**Comment by maread99** [comment]
Thanks for the reply.

All working on updating to openbb 3.1.0 (as released 22/06/23).

I had pywry 0.5.13 installed which I believe is still the latest version.

Thank you!
