### ISSUE TITLE
[Bug] v3.2: `/reports/economy` : Error: 'module' object is not callable

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5247]
Windows, v3.2 installer version:

![Screenshot 2023-07-24 095058](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/92635290-681a-4ed1-9ffc-5abe7f203e42)

**Comment by jmaslek** [comment]
Installer?  My dev is running this:

![Screenshot 2023-07-24 at 12 55 08 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/c6f10f88-cd90-4fe0-b21c-7ce0fec9d427)

**Comment by deeleeramone** [comment]
Installer

**Comment by deeleeramone** [comment]
> Installer? 

Both Mac and Windows:

```
(🦋) /reports/ $ economy

Executing:   0%|                                                                                                                                                             | 0/29 [00:00<?, ?cell/s]--- Logging error ---
Traceback (most recent call last):
  File "jupyter_client/manager.py", line 85, in wrapper
  File "jupyter_client/manager.py", line 397, in _async_start_kernel
  File "jupyter_client/manager.py", line 357, in _async_pre_start_kernel
  File "jupyter_client/provisioning/factory.py", line 101, in create_provisioner_instance
TypeError: 'module' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1083, in emit
  File "logging/__init__.py", line 927, in format
  File "openbb_terminal/core/log/generation/formatter_with_exceptions.py", line 169, in format
    record.msg = record.msg.replace("|", "-MOCK_PIPE-")
AttributeError: 'TypeError' object has no attribute 'replace'
Call stack:
  File "threading.py", line 937, in _bootstrap
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "openbb_terminal/decorators.py", line 71, in wrapper
    value = func(*args, **kwargs)
  File "openbb_terminal/reports/reports_model.py", line 308, in execute_notebook
    result = pm.execute_notebook(
  File "papermill/execute.py", line 113, in execute_notebook
  File "papermill/engines.py", line 48, in execute_notebook_with_engine
  File "papermill/engines.py", line 365, in execute_notebook
  File "papermill/engines.py", line 434, in execute_managed_notebook
  File "papermill/clientwrap.py", line 43, in execute
  File "contextlib.py", line 119, in __enter__
  File "nbclient/client.py", line 599, in setup_kernel
  File "nbclient/util.py", line 85, in wrapped
  File "nbclient/util.py", line 60, in just_run
  File "asyncio/base_events.py", line 634, in run_until_complete
  File "asyncio/base_events.py", line 601, in run_forever
  File "asyncio/base_events.py", line 1905, in _run_once
  File "asyncio/events.py", line 80, in _run
  File "nbclient/client.py", line 549, in async_start_new_kernel
  File "nbclient/util.py", line 97, in ensure_async
  File "jupyter_client/manager.py", line 92, in wrapper
  File "logging/__init__.py", line 1481, in exception
  File "logging/__init__.py", line 1475, in error
  File "logging/__init__.py", line 1589, in _log
  File "logging/__init__.py", line 1599, in handle
  File "logging/__init__.py", line 1661, in callHandlers
  File "logging/__init__.py", line 952, in handle
  File "logging/handlers.py", line 75, in emit
  File "logging/__init__.py", line 1187, in emit
  File "logging/__init__.py", line 1091, in emit
Message: TypeError("'module' object is not callable")
Arguments: ()
Executing:   0%|                                                                                                                                                             | 0/29 [00:00<?, ?cell/s]
Error: 'module' object is not callable
```

**Comment by deeleeramone** [comment]
fixed with #5250
