### ISSUE TITLE
[Bug] Candle function from stocks seems broken

### ISSUE THREAD

**Issue by elyak123** [OpenBB-finance/OpenBBTerminal#5445]
**Describe the bug**
When calling a plot candle function an error trace is displayed

**To Reproduce**
These are the following steps to reproduce:
```
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52)
[Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openbb_terminal.sdk import openbb
>>> openbb.stocks.candle("SPY")
Loading Daily data for SPY with starting period 2020-09-14.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/sdk/sdk_helpers.py", line 107, in __call__
    method_result = method(*args, **kwargs)
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/stocks/stocks_helper.py", line 649, in display_candle
    fig = PlotlyTA.plot(data, dict(**kwargs))
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/plots/plotly_ta/ta_class.py", line 214, in plot
    return PlotlyTA().__plot__(
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/plots/plotly_ta/ta_class.py", line 171, in __plot__
    return self.plot_fig(
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/plots/plotly_ta/ta_class.py", line 437, in plot_fig
    figure = self.process_fig(figure, volume_ticks_x)
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/plots/plotly_ta/ta_class.py", line 572, in process_fig
    new_subplot.add_inchart_volume(
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/plots/plotly_helper.py", line 978, in add_inchart_volume
    vol_scale = self.chart_volume_scaling(df_stock[volume_col], volume_ticks_x)
  File "/Users/javierllamas/anaconda3/envs/pqn/lib/python3.9/site-packages/openbb_terminal/core/plots/plotly_helper.py", line 930, in chart_volume_scaling
    volume_ticks = int(df_volume.max().max())
AttributeError: 'float' object has no attribute 'max'
```

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

<img width="1511" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/8533332/3616cf5b-bb4e-4ecc-8bfc-f8100c20654e">

<img width="1512" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/8533332/33a9caba-bb8e-44a3-82e4-7b947f1f2cec">

**Desktop (please complete the following information):**

- OS: [e.g. Mac Monterey]
- Python version [e.g. 3.9.13]

**Additional context**

* This issue was also reproduced in an x86 ubuntu operating system.
* By inspecting the code, seems to be that when changing from `volume_ticks = int(df_volume.max().max()` to `volume_ticks = int(df_volume.max())` at the `chart_volume_scaling` method at `openbb_terminal.core.plots.plotly_helper.py` the issue seems to be fixed, however I noticed that that line has about six months old.
* The following is a screenshot of the graph after removing the extra `.max()`:
<img width="972" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/8533332/06b6d9f5-e05d-40d7-900e-d824a75207b1">

**Comment by deeleeramone** [comment]
This issue is actually caused by a package which is not part of our library. It can be resolved with: 

```
pip uninstall bottleneck
```

**Comment by elyak123** [comment]
Would you guys want me to submit a PR with a try-except just for compatibility's sake?? Or that would be even more confusing??
I was thinking something like:
```
try:
    volume_ticks = int(df_volume.max().max())
except AttributeError:
    volume_ticks = int(df_volume.max())
```
Happy to help.

**Comment by deeleeramone** [comment]
> Would you guys want me to submit a PR with a try-except just for compatibility's sake?? Or that would be even more confusing?? I was thinking something like:
> 
> ```
> try:
>     volume_ticks = int(df_volume.max().max())
> except AttributeError:
>     volume_ticks = int(df_volume.max())
> ```
> 
> Happy to help.

I believe the exceptions for handling this are in #5446.  It will be available through the nightly build this evening.

**Comment by elyak123** [comment]
Awesome! closing this one then. Thanks a lot for all the work!!
