### ISSUE TITLE
[Bug] packaged installer crashes on M1 Mac running Sonoma

### ISSUE THREAD

**Issue by tidux** [OpenBB-finance/OpenBBTerminal#5881]
```
  ___                   ____  ____    _____                   _             _
 / _ \ _ __   ___ _ __ | __ )| __ )  |_   _|__ _ __ _ __ ___ (_)_ __   __ _| |
| | | | '_ \ / _ \ '_ \|  _ \|  _ \    | |/ _ \ '__| '_ ` _ \| | '_ \ / _` | |
| |_| | |_) |  __/ | | | |_) | |_) |   | |  __/ |  | | | | | | | | | | (_| | |
 \___/| .__/ \___|_| |_|____/|____/    |_|\___|_|  |_| |_| |_|_|_| |_|\__,_|_|
      |_|
                                    @@@
                                    @@@
             @@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@@@@@
             @@@                 @@@   @@@                 @@@
             @@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@@@@@
                                 @@@   @@@
                %%%%%%%%%%%%%%%%%@@@   @@@%%%%%%%%%%%%%%%%%
                @@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@@
                @@@              @@@   @@@              @@@
                @@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@@

                Investment research for everyone, anywhere.


Welcome to OpenBB Terminal! Please login to continue.

If the window is closed you can continue by pressing Ctrl+C.

Logging in... Please wait.

Traceback (most recent call last):
  File "terminal.py", line 44, in <module>
  File "terminal.py", line 39, in main
  File "openbb_terminal/core/session/session_controller.py", line 194, in main
  File "openbb_terminal/core/session/session_controller.py", line 113, in pywry_login
  File "openbb_terminal/core/session/session_controller.py", line 167, in login_and_launch
  File "openbb_terminal/core/session/session_controller.py", line 147, in launch_terminal
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/terminal_controller.py", line 48, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/reports/reports_model.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ipykernel/kernelapp.py", line 52, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ipykernel/ipkernel.py", line 20, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ipykernel/comm/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ipykernel/comm/comm.py", line 15, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ipykernel/kernelbase.py", line 38, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "psutil/__init__.py", line 241, in <module>
ImportError: version conflict: '/Applications/OpenBB Terminal/.OpenBB/psutil/_psutil_osx.cpython-39-darwin.so' C extension module was built for another version of psutil (5.9.3 instead of 5.9.5); you may try to 'pip uninstall psutil', manually remove /Applications/OpenBB Terminal/.OpenBB/psutil/_psutil_osx.cpython-39-darwin.so or clean the virtual env somehow, then reinstall
[2389] Failed to execute script 'terminal' due to unhandled exception!
```

**Comment by tidux** [comment]
As a workaround, running `brew install python-psutil && sudo rm '/Applications/OpenBB Terminal/.OpenBB/psutil/_psutil_osx.cpython-39-darwin.so'` seems to work.

**Comment by deeleeramone** [comment]
This error most likely occurred because the installation was done over top of an existing one, and there are now two versions of the psutil package.  The solution is to delete the offending one, or to move the entire application folder to the trash and re-install.

**Comment by tidux** [comment]
It was not done over the top of an existing one.  Homebrew and OpenBB exist in completely different folder locations.

**Comment by deeleeramone** [comment]
What I meant is, a previous version of OpenBB.

**Comment by tidux** [comment]
That is not correct either, this was my first attempt to install OpenBB on this Mac.
