### ISSUE TITLE
[Bug] Receiving TypeError after login

### ISSUE THREAD

**Issue by TheScriptGuy** [OpenBB-finance/OpenBBTerminal#6065]
**Describe the bug**
Receiving Traceback after login window closes.

Traceback (most recent call last):
  File "terminal.py", line 44, in <module>
  File "terminal.py", line 39, in main
  File "openbb_terminal/core/session/session_controller.py", line 192, in main
  File "openbb_terminal/core/session/session_controller.py", line 171, in login_and_launch
  File "openbb_terminal/core/session/session_controller.py", line 113, in pywry_login
  File "openbb_terminal/core/session/session_controller.py", line 167, in login_and_launch
  File "openbb_terminal/core/session/session_controller.py", line 147, in launch_terminal
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/terminal_controller.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/reports/reports_model.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "nbformat/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "nbformat/_version.py", line 28, in <module>
TypeError: expected string or bytes-like object
[39613] Failed to execute script 'terminal' due to unhandled exception!

**To Reproduce**
Run OpenBB Terminal, login window opens, I type in my credentials. Login window closes.

Traceback is thrown:
Traceback (most recent call last):
  File "terminal.py", line 44, in <module>
  File "terminal.py", line 39, in main
  File "openbb_terminal/core/session/session_controller.py", line 192, in main
  File "openbb_terminal/core/session/session_controller.py", line 171, in login_and_launch
  File "openbb_terminal/core/session/session_controller.py", line 113, in pywry_login
  File "openbb_terminal/core/session/session_controller.py", line 167, in login_and_launch
  File "openbb_terminal/core/session/session_controller.py", line 147, in launch_terminal
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/terminal_controller.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/reports/reports_model.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "nbformat/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "nbformat/_version.py", line 28, in <module>
TypeError: expected string or bytes-like object
[39613] Failed to execute script 'terminal' due to unhandled exception!

**Screenshots**
<img width="1410" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/29375323/c17f7ee2-96f6-4e98-8c7e-c52b58520d48">

**Desktop (please complete the following information):**

- OS: `Mac Sonoma 14.1.1 (M1)`
- Python `3.11.7`
- OpenBB Terminal `3.2.4`

**Additional context**
I'm performing SSL decryption upstream (corporate network). 
I've appended my corporate Root CA certificates into `/Applications/OpenBB\ Terminal/.OpenBB/certifi/cacert.pem`

**Comment by TheScriptGuy** [comment]
Is there a list of hostnames that should not be decrypted due to certificate pinning/client authentication when using the OpenBB Terminal?

**Comment by deeleeramone** [comment]
> Is there a list of hostnames that should not be decrypted due to certificate pinning/client authentication when using the OpenBB Terminal?



> Is there a list of hostnames that should not be decrypted due to certificate pinning/client authentication when using the OpenBB Terminal?

In short, no, there is not any such list.  Window creation is handled by an application, `/Applications/OpenBB\ Terminal/.OpenBB/pywry`, and communicates via localhost. `openbb.co` might need to be added to your list of domains, and modifying the `.env` file to include the network proxy address could help:

```
HTTP_PROXY="<ADDRESS>" or HTTPS_PROXY="<ADDRESS>”
```
