### ISSUE TITLE
[Bug] obb.currency.snapshots example does not work

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#6391]
From the docstring:
```
    Examples
    --------
    >>> from openbb import obb
    >>> obb.currency.snapshots(provider='fmp')
    >>> # Get exchange rates from USD and XAU to EUR, JPY, and GBP using 'fmp' as provider.
    >>> obb.currency.snapshots(provider='fmp', base='USD,XAU', counter_currencies='EUR,JPY,GBP', quote_type='indirect')
```

Running it gives:

```
>>> obb.currency.snapshots(provider='fmp', base='USD,XAU', counter_currencies='EUR,JPY,GBP', quote_type='indirect')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/james/VSCode/openbb-portfolio/.venv/lib/python3.10/site-packages/openbb_core/app/static/utils/decorators.py", line 89, in wrapper
    raise OpenBBError(
  File "/Users/james/VSCode/openbb-portfolio/.venv/lib/python3.10/site-packages/openbb_core/app/command_runner.py", line 384, in _execute_func
    raise OpenBBError(e) from e
openbb_core.app.model.abstract.error.OpenBBError: 
Type -> ValidationError

Detail -> 1 validation error for FMPCurrencySnapshotsData
counterCurrency
  Field required [type=missing, input_value={'index': 'EUR', 'base_cu...:40:54+0000', tz='UTC')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7
```

**Comment by deeleeramone** [comment]
Cannot recreate here both examples work as expected:
![Screenshot 2024-05-10 at 10 46 45 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/a59a4474-ed92-4503-aed6-0d674252c90e)
